# General Configuration
version: '{build}'

init:
  - ps: |
      If($Env:APPVEYOR_REPO_TAG -eq "true")
      {
        Write-Host "We now have a tagged release. Proper."
        Write-Host "Tag is $Env:APPVEYOR_REPO_TAG_NAME"
        $env:APPVEYOR_BUILD_VERSION=$env:APPVEYOR_REPO_TAG_NAME
        Update-AppveyorBuild -Version "$Env:APPVEYOR_REPO_TAG_NAME"
      } 
      else 
      {
        $releases = "https://api.github.com/repos/$env:APPVEYOR_REPO_NAME/releases"
        $tag = (Invoke-WebRequest $releases | ConvertFrom-Json)[0].tag_name
        $spl = $tag.Split("-")[0]
        Update-AppveyorBuild -Version "$spl.$Env:APPVEYOR_BUILD_VERSION-wip"
      }
      Write-Host "Hello. Build version is: $Env:APPVEYOR_BUILD_VERSION"

# Environment Configuration
image: Visual Studio 2019
cache:
  - '%LocalAppData%\NuGet\v3-cache'

install:
  #init and update submodules
  - git submodule update --recursive --init

 # version
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'

# Build Configuration
platform: Any CPU
configuration: Release

before_build:
  - nuget restore

build:  
  publish_nuget: true
  include_nuget_references: true
  publish_nuget_symbols: true
  use_snupkg_format: true
  project: SpeckleCoreGeometryClasses\SpeckleCoreGeometryClasses.csproj
  verbosity: minimal

# after_build:
#   # remove garbage
#   - ps: |
#       Remove-Item "$Env:APPVEYOR_BUILD_FOLDER\SpeckleCoreGeometryClasses\bin\Release\x86" -Recurse -ErrorAction Ignore
#       Remove-Item "$Env:APPVEYOR_BUILD_FOLDER\SpeckleCoreGeometryClasses\bin\Release\x64" -Recurse -ErrorAction Ignore

#deploy to nuget
deploy:
  - provider: NuGet
    symbol_server:           # remove to push symbols to SymbolSource.org
    server:                  # remove to push to NuGet.org
    api_key:
      secure: n4EiHDLVSLjOzqT7OOOg3US3PWs6fNsOaGpyT/EFBKrTKl/1wMmmKt73MNuTngD+
    skip_symbols: false
    artifact: /.*(\.|\.s)nupkg/
    on:
      appveyor_repo_tag: true


